//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CititorDto", Namespace="http://schemas.datacontract.org/2004/07/Service.Dto", IsReference=true)]
    public partial class CititorDto : object
    {
        
        private string AdresaField;
        
        private int CititorIdField;
        
        private string EmailField;
        
        private ServiceReference1.ImprumutDto[] ImprumutsField;
        
        private string NumeField;
        
        private string PrenumeField;
        
        private short StareField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adresa
        {
            get
            {
                return this.AdresaField;
            }
            set
            {
                this.AdresaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CititorId
        {
            get
            {
                return this.CititorIdField;
            }
            set
            {
                this.CititorIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ImprumutDto[] Imprumuts
        {
            get
            {
                return this.ImprumutsField;
            }
            set
            {
                this.ImprumutsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nume
        {
            get
            {
                return this.NumeField;
            }
            set
            {
                this.NumeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenume
        {
            get
            {
                return this.PrenumeField;
            }
            set
            {
                this.PrenumeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Stare
        {
            get
            {
                return this.StareField;
            }
            set
            {
                this.StareField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImprumutDto", Namespace="http://schemas.datacontract.org/2004/07/Service.Dto", IsReference=true)]
    public partial class ImprumutDto : object
    {
        
        private ServiceReference1.CarteDto CarteField;
        
        private int CarteIdField;
        
        private ServiceReference1.CititorDto CititorField;
        
        private int CititorIdField;
        
        private System.DateTime DataImprumutField;
        
        private System.Nullable<System.DateTime> DataRestituireField;
        
        private System.DateTime DataScadentaField;
        
        private int ImprumutIdField;
        
        private ServiceReference1.ReviewDto[] ReviewsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.CarteDto Carte
        {
            get
            {
                return this.CarteField;
            }
            set
            {
                this.CarteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CarteId
        {
            get
            {
                return this.CarteIdField;
            }
            set
            {
                this.CarteIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.CititorDto Cititor
        {
            get
            {
                return this.CititorField;
            }
            set
            {
                this.CititorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CititorId
        {
            get
            {
                return this.CititorIdField;
            }
            set
            {
                this.CititorIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataImprumut
        {
            get
            {
                return this.DataImprumutField;
            }
            set
            {
                this.DataImprumutField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataRestituire
        {
            get
            {
                return this.DataRestituireField;
            }
            set
            {
                this.DataRestituireField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataScadenta
        {
            get
            {
                return this.DataScadentaField;
            }
            set
            {
                this.DataScadentaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ImprumutId
        {
            get
            {
                return this.ImprumutIdField;
            }
            set
            {
                this.ImprumutIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ReviewDto[] Reviews
        {
            get
            {
                return this.ReviewsField;
            }
            set
            {
                this.ReviewsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CarteDto", Namespace="http://schemas.datacontract.org/2004/07/Service.Dto", IsReference=true)]
    public partial class CarteDto : object
    {
        
        private ServiceReference1.AutorDto AutorField;
        
        private int AutorIdField;
        
        private int CarteIdField;
        
        private ServiceReference1.GenDto GenField;
        
        private int GenIdField;
        
        private ServiceReference1.ImprumutDto[] ImprumutsField;
        
        private string TitluField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.AutorDto Autor
        {
            get
            {
                return this.AutorField;
            }
            set
            {
                this.AutorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AutorId
        {
            get
            {
                return this.AutorIdField;
            }
            set
            {
                this.AutorIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CarteId
        {
            get
            {
                return this.CarteIdField;
            }
            set
            {
                this.CarteIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.GenDto Gen
        {
            get
            {
                return this.GenField;
            }
            set
            {
                this.GenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GenId
        {
            get
            {
                return this.GenIdField;
            }
            set
            {
                this.GenIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ImprumutDto[] Imprumuts
        {
            get
            {
                return this.ImprumutsField;
            }
            set
            {
                this.ImprumutsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titlu
        {
            get
            {
                return this.TitluField;
            }
            set
            {
                this.TitluField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReviewDto", Namespace="http://schemas.datacontract.org/2004/07/Service.Dto", IsReference=true)]
    public partial class ReviewDto : object
    {
        
        private ServiceReference1.ImprumutDto ImprumutField;
        
        private int ImprumutIdField;
        
        private int ReviewIdField;
        
        private string TextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ImprumutDto Imprumut
        {
            get
            {
                return this.ImprumutField;
            }
            set
            {
                this.ImprumutField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ImprumutId
        {
            get
            {
                return this.ImprumutIdField;
            }
            set
            {
                this.ImprumutIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReviewId
        {
            get
            {
                return this.ReviewIdField;
            }
            set
            {
                this.ReviewIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text
        {
            get
            {
                return this.TextField;
            }
            set
            {
                this.TextField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AutorDto", Namespace="http://schemas.datacontract.org/2004/07/Service.Dto", IsReference=true)]
    public partial class AutorDto : object
    {
        
        private int AutorIdField;
        
        private ServiceReference1.CarteDto[] CartesField;
        
        private string NumeField;
        
        private string PrenumeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AutorId
        {
            get
            {
                return this.AutorIdField;
            }
            set
            {
                this.AutorIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.CarteDto[] Cartes
        {
            get
            {
                return this.CartesField;
            }
            set
            {
                this.CartesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nume
        {
            get
            {
                return this.NumeField;
            }
            set
            {
                this.NumeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenume
        {
            get
            {
                return this.PrenumeField;
            }
            set
            {
                this.PrenumeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenDto", Namespace="http://schemas.datacontract.org/2004/07/Service.Dto", IsReference=true)]
    public partial class GenDto : object
    {
        
        private ServiceReference1.CarteDto[] CartesField;
        
        private string DescriereField;
        
        private int GenIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.CarteDto[] Cartes
        {
            get
            {
                return this.CartesField;
            }
            set
            {
                this.CartesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descriere
        {
            get
            {
                return this.DescriereField;
            }
            set
            {
                this.DescriereField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GenId
        {
            get
            {
                return this.GenIdField;
            }
            set
            {
                this.GenIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IBiblioteca")]
    public interface IBiblioteca
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/achizitie", ReplyAction="http://tempuri.org/IBiblioteca/achizitieResponse")]
        System.Threading.Tasks.Task achizitieAsync(string titluCarte, string descrieGen, string numeAutor, string prenumeAutor, int numar_de_inserari);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/realizareImprumut", ReplyAction="http://tempuri.org/IBiblioteca/realizareImprumutResponse")]
        System.Threading.Tasks.Task<int> realizareImprumutAsync(string genCarte, string titluCarte, string numeCititor, string prenumeCititor, string adresaCititor, string emailCititior);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/restituire", ReplyAction="http://tempuri.org/IBiblioteca/restituireResponse")]
        System.Threading.Tasks.Task restituireAsync(string numeCarte, string numeAutor, string prenumeAutor, string numeCititor, string prenumeCititor, string textReview);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/getCititoriPerioada", ReplyAction="http://tempuri.org/IBiblioteca/getCititoriPerioadaResponse")]
        System.Threading.Tasks.Task<ServiceReference1.CititorDto[]> getCititoriPerioadaAsync(System.DateTime startDate, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/getCartiSolicitate", ReplyAction="http://tempuri.org/IBiblioteca/getCartiSolicitateResponse")]
        System.Threading.Tasks.Task<ServiceReference1.CarteDto[]> getCartiSolicitateAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/getAutoriCautati", ReplyAction="http://tempuri.org/IBiblioteca/getAutoriCautatiResponse")]
        System.Threading.Tasks.Task<ServiceReference1.AutorDto[]> getAutoriCautatiAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/getGenuriCautate", ReplyAction="http://tempuri.org/IBiblioteca/getGenuriCautateResponse")]
        System.Threading.Tasks.Task<ServiceReference1.GenDto[]> getGenuriCautateAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/getReviews", ReplyAction="http://tempuri.org/IBiblioteca/getReviewsResponse")]
        System.Threading.Tasks.Task<ServiceReference1.ReviewDto[]> getReviewsAsync(ServiceReference1.CarteDto carte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/getAllGens", ReplyAction="http://tempuri.org/IBiblioteca/getAllGensResponse")]
        System.Threading.Tasks.Task<ServiceReference1.GenDto[]> getAllGensAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/existaCititor", ReplyAction="http://tempuri.org/IBiblioteca/existaCititorResponse")]
        System.Threading.Tasks.Task<bool> existaCititorAsync(string numeCititor, string prenumeCititor, string adresaCititor, string emailCititior);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/getCititorId", ReplyAction="http://tempuri.org/IBiblioteca/getCititorIdResponse")]
        System.Threading.Tasks.Task<int> getCititorIdAsync(string numeCititor, string prenumeCititor, string adresaCititor, string emailCititior);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/getCartiDupaGen", ReplyAction="http://tempuri.org/IBiblioteca/getCartiDupaGenResponse")]
        System.Threading.Tasks.Task<ServiceReference1.CarteDto[]> getCartiDupaGenAsync(int idGen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/getStare", ReplyAction="http://tempuri.org/IBiblioteca/getStareResponse")]
        System.Threading.Tasks.Task<short> getStareAsync(int cititorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/getAutorIdByName", ReplyAction="http://tempuri.org/IBiblioteca/getAutorIdByNameResponse")]
        System.Threading.Tasks.Task<int> getAutorIdByNameAsync(string nume, string prenume);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/getGenIdByName", ReplyAction="http://tempuri.org/IBiblioteca/getGenIdByNameResponse")]
        System.Threading.Tasks.Task<int> getGenIdByNameAsync(string descriere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/getStareCititor", ReplyAction="http://tempuri.org/IBiblioteca/getStareCititorResponse")]
        System.Threading.Tasks.Task<short> getStareCititorAsync(string numeCititor, string prenumeCititor, string adresaCititor, string emailCititior);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/getGenCarteDescriere", ReplyAction="http://tempuri.org/IBiblioteca/getGenCarteDescriereResponse")]
        System.Threading.Tasks.Task<string> getGenCarteDescriereAsync(int genId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/getCarteByName", ReplyAction="http://tempuri.org/IBiblioteca/getCarteByNameResponse")]
        System.Threading.Tasks.Task<ServiceReference1.CarteDto> getCarteByNameAsync(string numeCarte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/getTitluCarteById", ReplyAction="http://tempuri.org/IBiblioteca/getTitluCarteByIdResponse")]
        System.Threading.Tasks.Task<string> getTitluCarteByIdAsync(int idCarte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/GetCititorById", ReplyAction="http://tempuri.org/IBiblioteca/GetCititorByIdResponse")]
        System.Threading.Tasks.Task<ServiceReference1.CititorDto> GetCititorByIdAsync(int idCititor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/getGenIdByCarteId", ReplyAction="http://tempuri.org/IBiblioteca/getGenIdByCarteIdResponse")]
        System.Threading.Tasks.Task<int> getGenIdByCarteIdAsync(int carteId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface IBibliotecaChannel : ServiceReference1.IBiblioteca, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class BibliotecaClient : System.ServiceModel.ClientBase<ServiceReference1.IBiblioteca>, ServiceReference1.IBiblioteca
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public BibliotecaClient() : 
                base(BibliotecaClient.GetDefaultBinding(), BibliotecaClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IBiblioteca.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BibliotecaClient(EndpointConfiguration endpointConfiguration) : 
                base(BibliotecaClient.GetBindingForEndpoint(endpointConfiguration), BibliotecaClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BibliotecaClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(BibliotecaClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BibliotecaClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(BibliotecaClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BibliotecaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task achizitieAsync(string titluCarte, string descrieGen, string numeAutor, string prenumeAutor, int numar_de_inserari)
        {
            return base.Channel.achizitieAsync(titluCarte, descrieGen, numeAutor, prenumeAutor, numar_de_inserari);
        }
        
        public System.Threading.Tasks.Task<int> realizareImprumutAsync(string genCarte, string titluCarte, string numeCititor, string prenumeCititor, string adresaCititor, string emailCititior)
        {
            return base.Channel.realizareImprumutAsync(genCarte, titluCarte, numeCititor, prenumeCititor, adresaCititor, emailCititior);
        }
        
        public System.Threading.Tasks.Task restituireAsync(string numeCarte, string numeAutor, string prenumeAutor, string numeCititor, string prenumeCititor, string textReview)
        {
            return base.Channel.restituireAsync(numeCarte, numeAutor, prenumeAutor, numeCititor, prenumeCititor, textReview);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CititorDto[]> getCititoriPerioadaAsync(System.DateTime startDate, System.DateTime endDate)
        {
            return base.Channel.getCititoriPerioadaAsync(startDate, endDate);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CarteDto[]> getCartiSolicitateAsync()
        {
            return base.Channel.getCartiSolicitateAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.AutorDto[]> getAutoriCautatiAsync()
        {
            return base.Channel.getAutoriCautatiAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GenDto[]> getGenuriCautateAsync()
        {
            return base.Channel.getGenuriCautateAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ReviewDto[]> getReviewsAsync(ServiceReference1.CarteDto carte)
        {
            return base.Channel.getReviewsAsync(carte);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GenDto[]> getAllGensAsync()
        {
            return base.Channel.getAllGensAsync();
        }
        
        public System.Threading.Tasks.Task<bool> existaCititorAsync(string numeCititor, string prenumeCititor, string adresaCititor, string emailCititior)
        {
            return base.Channel.existaCititorAsync(numeCititor, prenumeCititor, adresaCititor, emailCititior);
        }
        
        public System.Threading.Tasks.Task<int> getCititorIdAsync(string numeCititor, string prenumeCititor, string adresaCititor, string emailCititior)
        {
            return base.Channel.getCititorIdAsync(numeCititor, prenumeCititor, adresaCititor, emailCititior);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CarteDto[]> getCartiDupaGenAsync(int idGen)
        {
            return base.Channel.getCartiDupaGenAsync(idGen);
        }
        
        public System.Threading.Tasks.Task<short> getStareAsync(int cititorId)
        {
            return base.Channel.getStareAsync(cititorId);
        }
        
        public System.Threading.Tasks.Task<int> getAutorIdByNameAsync(string nume, string prenume)
        {
            return base.Channel.getAutorIdByNameAsync(nume, prenume);
        }
        
        public System.Threading.Tasks.Task<int> getGenIdByNameAsync(string descriere)
        {
            return base.Channel.getGenIdByNameAsync(descriere);
        }
        
        public System.Threading.Tasks.Task<short> getStareCititorAsync(string numeCititor, string prenumeCititor, string adresaCititor, string emailCititior)
        {
            return base.Channel.getStareCititorAsync(numeCititor, prenumeCititor, adresaCititor, emailCititior);
        }
        
        public System.Threading.Tasks.Task<string> getGenCarteDescriereAsync(int genId)
        {
            return base.Channel.getGenCarteDescriereAsync(genId);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CarteDto> getCarteByNameAsync(string numeCarte)
        {
            return base.Channel.getCarteByNameAsync(numeCarte);
        }
        
        public System.Threading.Tasks.Task<string> getTitluCarteByIdAsync(int idCarte)
        {
            return base.Channel.getTitluCarteByIdAsync(idCarte);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CititorDto> GetCititorByIdAsync(int idCititor)
        {
            return base.Channel.GetCititorByIdAsync(idCititor);
        }
        
        public System.Threading.Tasks.Task<int> getGenIdByCarteIdAsync(int carteId)
        {
            return base.Channel.getGenIdByCarteIdAsync(carteId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IBiblioteca))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IBiblioteca))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8081/biblio");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return BibliotecaClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IBiblioteca);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return BibliotecaClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IBiblioteca);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IBiblioteca,
        }
    }
}
