//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Dto
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CititorDto", Namespace="http://schemas.datacontract.org/2004/07/Service.Dto", IsReference=true)]
    public partial class CititorDto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AdresaField;
        
        private int CititorIdField;
        
        private string EmailField;
        
        private Service.Dto.ImprumutDto[] ImprumutsField;
        
        private string NumeField;
        
        private string PrenumeField;
        
        private short StareField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adresa
        {
            get
            {
                return this.AdresaField;
            }
            set
            {
                this.AdresaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CititorId
        {
            get
            {
                return this.CititorIdField;
            }
            set
            {
                this.CititorIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Service.Dto.ImprumutDto[] Imprumuts
        {
            get
            {
                return this.ImprumutsField;
            }
            set
            {
                this.ImprumutsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nume
        {
            get
            {
                return this.NumeField;
            }
            set
            {
                this.NumeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenume
        {
            get
            {
                return this.PrenumeField;
            }
            set
            {
                this.PrenumeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Stare
        {
            get
            {
                return this.StareField;
            }
            set
            {
                this.StareField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImprumutDto", Namespace="http://schemas.datacontract.org/2004/07/Service.Dto", IsReference=true)]
    public partial class ImprumutDto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Service.Dto.CarteDto CarteField;
        
        private int CarteIdField;
        
        private Service.Dto.CititorDto CititorField;
        
        private int CititorIdField;
        
        private System.DateTime DataImprumutField;
        
        private System.Nullable<System.DateTime> DataRestituireField;
        
        private System.DateTime DataScadentaField;
        
        private int ImprumutIdField;
        
        private Service.Dto.ReviewDto[] ReviewsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Service.Dto.CarteDto Carte
        {
            get
            {
                return this.CarteField;
            }
            set
            {
                this.CarteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CarteId
        {
            get
            {
                return this.CarteIdField;
            }
            set
            {
                this.CarteIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Service.Dto.CititorDto Cititor
        {
            get
            {
                return this.CititorField;
            }
            set
            {
                this.CititorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CititorId
        {
            get
            {
                return this.CititorIdField;
            }
            set
            {
                this.CititorIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataImprumut
        {
            get
            {
                return this.DataImprumutField;
            }
            set
            {
                this.DataImprumutField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataRestituire
        {
            get
            {
                return this.DataRestituireField;
            }
            set
            {
                this.DataRestituireField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataScadenta
        {
            get
            {
                return this.DataScadentaField;
            }
            set
            {
                this.DataScadentaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ImprumutId
        {
            get
            {
                return this.ImprumutIdField;
            }
            set
            {
                this.ImprumutIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Service.Dto.ReviewDto[] Reviews
        {
            get
            {
                return this.ReviewsField;
            }
            set
            {
                this.ReviewsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CarteDto", Namespace="http://schemas.datacontract.org/2004/07/Service.Dto", IsReference=true)]
    public partial class CarteDto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Service.Dto.AutorDto AutorField;
        
        private int AutorIdField;
        
        private int CarteIdField;
        
        private Service.Dto.GenDto GenField;
        
        private int GenIdField;
        
        private Service.Dto.ImprumutDto[] ImprumutsField;
        
        private string TitluField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Service.Dto.AutorDto Autor
        {
            get
            {
                return this.AutorField;
            }
            set
            {
                this.AutorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AutorId
        {
            get
            {
                return this.AutorIdField;
            }
            set
            {
                this.AutorIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CarteId
        {
            get
            {
                return this.CarteIdField;
            }
            set
            {
                this.CarteIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Service.Dto.GenDto Gen
        {
            get
            {
                return this.GenField;
            }
            set
            {
                this.GenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GenId
        {
            get
            {
                return this.GenIdField;
            }
            set
            {
                this.GenIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Service.Dto.ImprumutDto[] Imprumuts
        {
            get
            {
                return this.ImprumutsField;
            }
            set
            {
                this.ImprumutsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titlu
        {
            get
            {
                return this.TitluField;
            }
            set
            {
                this.TitluField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReviewDto", Namespace="http://schemas.datacontract.org/2004/07/Service.Dto", IsReference=true)]
    public partial class ReviewDto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Service.Dto.ImprumutDto ImprumutField;
        
        private int ImprumutIdField;
        
        private int ReviewIdField;
        
        private string TextField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Service.Dto.ImprumutDto Imprumut
        {
            get
            {
                return this.ImprumutField;
            }
            set
            {
                this.ImprumutField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ImprumutId
        {
            get
            {
                return this.ImprumutIdField;
            }
            set
            {
                this.ImprumutIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReviewId
        {
            get
            {
                return this.ReviewIdField;
            }
            set
            {
                this.ReviewIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text
        {
            get
            {
                return this.TextField;
            }
            set
            {
                this.TextField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AutorDto", Namespace="http://schemas.datacontract.org/2004/07/Service.Dto", IsReference=true)]
    public partial class AutorDto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AutorIdField;
        
        private Service.Dto.CarteDto[] CartesField;
        
        private string NumeField;
        
        private string PrenumeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AutorId
        {
            get
            {
                return this.AutorIdField;
            }
            set
            {
                this.AutorIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Service.Dto.CarteDto[] Cartes
        {
            get
            {
                return this.CartesField;
            }
            set
            {
                this.CartesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nume
        {
            get
            {
                return this.NumeField;
            }
            set
            {
                this.NumeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenume
        {
            get
            {
                return this.PrenumeField;
            }
            set
            {
                this.PrenumeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenDto", Namespace="http://schemas.datacontract.org/2004/07/Service.Dto", IsReference=true)]
    public partial class GenDto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Service.Dto.CarteDto[] CartesField;
        
        private string DescriereField;
        
        private int GenIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Service.Dto.CarteDto[] Cartes
        {
            get
            {
                return this.CartesField;
            }
            set
            {
                this.CartesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descriere
        {
            get
            {
                return this.DescriereField;
            }
            set
            {
                this.DescriereField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GenId
        {
            get
            {
                return this.GenIdField;
            }
            set
            {
                this.GenIdField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IBiblioteca")]
public interface IBiblioteca
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/achizitie", ReplyAction="http://tempuri.org/IBiblioteca/achizitieResponse")]
    void achizitie(string titluCarte, string descrieGen, string numeAutor, string prenumeAutor, int numar_de_inserari);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/achizitie", ReplyAction="http://tempuri.org/IBiblioteca/achizitieResponse")]
    System.Threading.Tasks.Task achizitieAsync(string titluCarte, string descrieGen, string numeAutor, string prenumeAutor, int numar_de_inserari);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/realizareImprumut", ReplyAction="http://tempuri.org/IBiblioteca/realizareImprumutResponse")]
    int realizareImprumut(string genCarte, string titluCarte, string numeCititor, string prenumeCititor, string adresaCititor, string emailCititior);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/realizareImprumut", ReplyAction="http://tempuri.org/IBiblioteca/realizareImprumutResponse")]
    System.Threading.Tasks.Task<int> realizareImprumutAsync(string genCarte, string titluCarte, string numeCititor, string prenumeCititor, string adresaCititor, string emailCititior);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/restituire", ReplyAction="http://tempuri.org/IBiblioteca/restituireResponse")]
    void restituire(string numeCarte, string numeAutor, string prenumeAutor, string numeCititor, string prenumeCititor, string textReview);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/restituire", ReplyAction="http://tempuri.org/IBiblioteca/restituireResponse")]
    System.Threading.Tasks.Task restituireAsync(string numeCarte, string numeAutor, string prenumeAutor, string numeCititor, string prenumeCititor, string textReview);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/getCititoriPerioada", ReplyAction="http://tempuri.org/IBiblioteca/getCititoriPerioadaResponse")]
    Service.Dto.CititorDto[] getCititoriPerioada(System.DateTime startDate, System.DateTime endDate);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/getCititoriPerioada", ReplyAction="http://tempuri.org/IBiblioteca/getCititoriPerioadaResponse")]
    System.Threading.Tasks.Task<Service.Dto.CititorDto[]> getCititoriPerioadaAsync(System.DateTime startDate, System.DateTime endDate);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/getCartiSolicitate", ReplyAction="http://tempuri.org/IBiblioteca/getCartiSolicitateResponse")]
    Service.Dto.CarteDto[] getCartiSolicitate();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/getCartiSolicitate", ReplyAction="http://tempuri.org/IBiblioteca/getCartiSolicitateResponse")]
    System.Threading.Tasks.Task<Service.Dto.CarteDto[]> getCartiSolicitateAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/getAutoriCautati", ReplyAction="http://tempuri.org/IBiblioteca/getAutoriCautatiResponse")]
    Service.Dto.AutorDto[] getAutoriCautati();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/getAutoriCautati", ReplyAction="http://tempuri.org/IBiblioteca/getAutoriCautatiResponse")]
    System.Threading.Tasks.Task<Service.Dto.AutorDto[]> getAutoriCautatiAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/getGenuriCautate", ReplyAction="http://tempuri.org/IBiblioteca/getGenuriCautateResponse")]
    Service.Dto.GenDto[] getGenuriCautate();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/getGenuriCautate", ReplyAction="http://tempuri.org/IBiblioteca/getGenuriCautateResponse")]
    System.Threading.Tasks.Task<Service.Dto.GenDto[]> getGenuriCautateAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/getReviews", ReplyAction="http://tempuri.org/IBiblioteca/getReviewsResponse")]
    Service.Dto.ReviewDto[] getReviews(Service.Dto.CarteDto carte);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/getReviews", ReplyAction="http://tempuri.org/IBiblioteca/getReviewsResponse")]
    System.Threading.Tasks.Task<Service.Dto.ReviewDto[]> getReviewsAsync(Service.Dto.CarteDto carte);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/getAllGens", ReplyAction="http://tempuri.org/IBiblioteca/getAllGensResponse")]
    Service.Dto.GenDto[] getAllGens();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/getAllGens", ReplyAction="http://tempuri.org/IBiblioteca/getAllGensResponse")]
    System.Threading.Tasks.Task<Service.Dto.GenDto[]> getAllGensAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/existaCititor", ReplyAction="http://tempuri.org/IBiblioteca/existaCititorResponse")]
    bool existaCititor(string numeCititor, string prenumeCititor, string adresaCititor, string emailCititior);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/existaCititor", ReplyAction="http://tempuri.org/IBiblioteca/existaCititorResponse")]
    System.Threading.Tasks.Task<bool> existaCititorAsync(string numeCititor, string prenumeCititor, string adresaCititor, string emailCititior);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/getCititorId", ReplyAction="http://tempuri.org/IBiblioteca/getCititorIdResponse")]
    int getCititorId(string numeCititor, string prenumeCititor, string adresaCititor, string emailCititior);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/getCititorId", ReplyAction="http://tempuri.org/IBiblioteca/getCititorIdResponse")]
    System.Threading.Tasks.Task<int> getCititorIdAsync(string numeCititor, string prenumeCititor, string adresaCititor, string emailCititior);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/getCartiDupaGen", ReplyAction="http://tempuri.org/IBiblioteca/getCartiDupaGenResponse")]
    Service.Dto.CarteDto[] getCartiDupaGen(int idGen);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/getCartiDupaGen", ReplyAction="http://tempuri.org/IBiblioteca/getCartiDupaGenResponse")]
    System.Threading.Tasks.Task<Service.Dto.CarteDto[]> getCartiDupaGenAsync(int idGen);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/getStare", ReplyAction="http://tempuri.org/IBiblioteca/getStareResponse")]
    short getStare(int cititorId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/getStare", ReplyAction="http://tempuri.org/IBiblioteca/getStareResponse")]
    System.Threading.Tasks.Task<short> getStareAsync(int cititorId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/getAutorIdByName", ReplyAction="http://tempuri.org/IBiblioteca/getAutorIdByNameResponse")]
    int getAutorIdByName(string nume, string prenume);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/getAutorIdByName", ReplyAction="http://tempuri.org/IBiblioteca/getAutorIdByNameResponse")]
    System.Threading.Tasks.Task<int> getAutorIdByNameAsync(string nume, string prenume);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/getGenIdByName", ReplyAction="http://tempuri.org/IBiblioteca/getGenIdByNameResponse")]
    int getGenIdByName(string descriere);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/getGenIdByName", ReplyAction="http://tempuri.org/IBiblioteca/getGenIdByNameResponse")]
    System.Threading.Tasks.Task<int> getGenIdByNameAsync(string descriere);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/getStareCititor", ReplyAction="http://tempuri.org/IBiblioteca/getStareCititorResponse")]
    short getStareCititor(string numeCititor, string prenumeCititor, string adresaCititor, string emailCititior);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/getStareCititor", ReplyAction="http://tempuri.org/IBiblioteca/getStareCititorResponse")]
    System.Threading.Tasks.Task<short> getStareCititorAsync(string numeCititor, string prenumeCititor, string adresaCititor, string emailCititior);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/getGenCarteDescriere", ReplyAction="http://tempuri.org/IBiblioteca/getGenCarteDescriereResponse")]
    string getGenCarteDescriere(int genId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/getGenCarteDescriere", ReplyAction="http://tempuri.org/IBiblioteca/getGenCarteDescriereResponse")]
    System.Threading.Tasks.Task<string> getGenCarteDescriereAsync(int genId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/getCarteByName", ReplyAction="http://tempuri.org/IBiblioteca/getCarteByNameResponse")]
    Service.Dto.CarteDto getCarteByName(string numeCarte);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioteca/getCarteByName", ReplyAction="http://tempuri.org/IBiblioteca/getCarteByNameResponse")]
    System.Threading.Tasks.Task<Service.Dto.CarteDto> getCarteByNameAsync(string numeCarte);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IBibliotecaChannel : IBiblioteca, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class BibliotecaClient : System.ServiceModel.ClientBase<IBiblioteca>, IBiblioteca
{
    
    public BibliotecaClient()
    {
    }
    
    public BibliotecaClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public BibliotecaClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BibliotecaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BibliotecaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void achizitie(string titluCarte, string descrieGen, string numeAutor, string prenumeAutor, int numar_de_inserari)
    {
        base.Channel.achizitie(titluCarte, descrieGen, numeAutor, prenumeAutor, numar_de_inserari);
    }
    
    public System.Threading.Tasks.Task achizitieAsync(string titluCarte, string descrieGen, string numeAutor, string prenumeAutor, int numar_de_inserari)
    {
        return base.Channel.achizitieAsync(titluCarte, descrieGen, numeAutor, prenumeAutor, numar_de_inserari);
    }
    
    public int realizareImprumut(string genCarte, string titluCarte, string numeCititor, string prenumeCititor, string adresaCititor, string emailCititior)
    {
        return base.Channel.realizareImprumut(genCarte, titluCarte, numeCititor, prenumeCititor, adresaCititor, emailCititior);
    }
    
    public System.Threading.Tasks.Task<int> realizareImprumutAsync(string genCarte, string titluCarte, string numeCititor, string prenumeCititor, string adresaCititor, string emailCititior)
    {
        return base.Channel.realizareImprumutAsync(genCarte, titluCarte, numeCititor, prenumeCititor, adresaCititor, emailCititior);
    }
    
    public void restituire(string numeCarte, string numeAutor, string prenumeAutor, string numeCititor, string prenumeCititor, string textReview)
    {
        base.Channel.restituire(numeCarte, numeAutor, prenumeAutor, numeCititor, prenumeCititor, textReview);
    }
    
    public System.Threading.Tasks.Task restituireAsync(string numeCarte, string numeAutor, string prenumeAutor, string numeCititor, string prenumeCititor, string textReview)
    {
        return base.Channel.restituireAsync(numeCarte, numeAutor, prenumeAutor, numeCititor, prenumeCititor, textReview);
    }
    
    public Service.Dto.CititorDto[] getCititoriPerioada(System.DateTime startDate, System.DateTime endDate)
    {
        return base.Channel.getCititoriPerioada(startDate, endDate);
    }
    
    public System.Threading.Tasks.Task<Service.Dto.CititorDto[]> getCititoriPerioadaAsync(System.DateTime startDate, System.DateTime endDate)
    {
        return base.Channel.getCititoriPerioadaAsync(startDate, endDate);
    }
    
    public Service.Dto.CarteDto[] getCartiSolicitate()
    {
        return base.Channel.getCartiSolicitate();
    }
    
    public System.Threading.Tasks.Task<Service.Dto.CarteDto[]> getCartiSolicitateAsync()
    {
        return base.Channel.getCartiSolicitateAsync();
    }
    
    public Service.Dto.AutorDto[] getAutoriCautati()
    {
        return base.Channel.getAutoriCautati();
    }
    
    public System.Threading.Tasks.Task<Service.Dto.AutorDto[]> getAutoriCautatiAsync()
    {
        return base.Channel.getAutoriCautatiAsync();
    }
    
    public Service.Dto.GenDto[] getGenuriCautate()
    {
        return base.Channel.getGenuriCautate();
    }
    
    public System.Threading.Tasks.Task<Service.Dto.GenDto[]> getGenuriCautateAsync()
    {
        return base.Channel.getGenuriCautateAsync();
    }
    
    public Service.Dto.ReviewDto[] getReviews(Service.Dto.CarteDto carte)
    {
        return base.Channel.getReviews(carte);
    }
    
    public System.Threading.Tasks.Task<Service.Dto.ReviewDto[]> getReviewsAsync(Service.Dto.CarteDto carte)
    {
        return base.Channel.getReviewsAsync(carte);
    }
    
    public Service.Dto.GenDto[] getAllGens()
    {
        return base.Channel.getAllGens();
    }
    
    public System.Threading.Tasks.Task<Service.Dto.GenDto[]> getAllGensAsync()
    {
        return base.Channel.getAllGensAsync();
    }
    
    public bool existaCititor(string numeCititor, string prenumeCititor, string adresaCititor, string emailCititior)
    {
        return base.Channel.existaCititor(numeCititor, prenumeCititor, adresaCititor, emailCititior);
    }
    
    public System.Threading.Tasks.Task<bool> existaCititorAsync(string numeCititor, string prenumeCititor, string adresaCititor, string emailCititior)
    {
        return base.Channel.existaCititorAsync(numeCititor, prenumeCititor, adresaCititor, emailCititior);
    }
    
    public int getCititorId(string numeCititor, string prenumeCititor, string adresaCititor, string emailCititior)
    {
        return base.Channel.getCititorId(numeCititor, prenumeCititor, adresaCititor, emailCititior);
    }
    
    public System.Threading.Tasks.Task<int> getCititorIdAsync(string numeCititor, string prenumeCititor, string adresaCititor, string emailCititior)
    {
        return base.Channel.getCititorIdAsync(numeCititor, prenumeCititor, adresaCititor, emailCititior);
    }
    
    public Service.Dto.CarteDto[] getCartiDupaGen(int idGen)
    {
        return base.Channel.getCartiDupaGen(idGen);
    }
    
    public System.Threading.Tasks.Task<Service.Dto.CarteDto[]> getCartiDupaGenAsync(int idGen)
    {
        return base.Channel.getCartiDupaGenAsync(idGen);
    }
    
    public short getStare(int cititorId)
    {
        return base.Channel.getStare(cititorId);
    }
    
    public System.Threading.Tasks.Task<short> getStareAsync(int cititorId)
    {
        return base.Channel.getStareAsync(cititorId);
    }
    
    public int getAutorIdByName(string nume, string prenume)
    {
        return base.Channel.getAutorIdByName(nume, prenume);
    }
    
    public System.Threading.Tasks.Task<int> getAutorIdByNameAsync(string nume, string prenume)
    {
        return base.Channel.getAutorIdByNameAsync(nume, prenume);
    }
    
    public int getGenIdByName(string descriere)
    {
        return base.Channel.getGenIdByName(descriere);
    }
    
    public System.Threading.Tasks.Task<int> getGenIdByNameAsync(string descriere)
    {
        return base.Channel.getGenIdByNameAsync(descriere);
    }
    
    public short getStareCititor(string numeCititor, string prenumeCititor, string adresaCititor, string emailCititior)
    {
        return base.Channel.getStareCititor(numeCititor, prenumeCititor, adresaCititor, emailCititior);
    }
    
    public System.Threading.Tasks.Task<short> getStareCititorAsync(string numeCititor, string prenumeCititor, string adresaCititor, string emailCititior)
    {
        return base.Channel.getStareCititorAsync(numeCititor, prenumeCititor, adresaCititor, emailCititior);
    }
    
    public string getGenCarteDescriere(int genId)
    {
        return base.Channel.getGenCarteDescriere(genId);
    }
    
    public System.Threading.Tasks.Task<string> getGenCarteDescriereAsync(int genId)
    {
        return base.Channel.getGenCarteDescriereAsync(genId);
    }
    
    public Service.Dto.CarteDto getCarteByName(string numeCarte)
    {
        return base.Channel.getCarteByName(numeCarte);
    }
    
    public System.Threading.Tasks.Task<Service.Dto.CarteDto> getCarteByNameAsync(string numeCarte)
    {
        return base.Channel.getCarteByNameAsync(numeCarte);
    }
}
